In [51]:
import pandas as pd

In [52]:
matches = pd.read_csv("../data/matches.csv", index_col=0).reset_index(drop=True)

In [53]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [54]:
matches.shape

(1389, 27)

In [55]:
matches["team"].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Manchester City             71
Arsenal                     71
Tottenham Hotspur           71
Wolverhampton Wanderers     71
Crystal Palace              71
Leeds United                71
Burnley                     71
Chelsea                     70
Leicester City              70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [56]:
matches["round"].value_counts()

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 23    39
Matchweek 24    39
Matchweek 25    39
Matchweek 26    39
Matchweek 28    39
Matchweek 29    39
Matchweek 31    39
Matchweek 32    39
Matchweek 34    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [57]:
matches.dtypes

date                str
time                str
comp                str
round               str
day                 str
venue               str
result              str
gf              float64
ga              float64
opponent            str
xg              float64
xga             float64
poss            float64
attendance      float64
captain             str
formation           str
referee             str
match report        str
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team                str
dtype: object

In [58]:
matches["date"] = pd.to_datetime(matches["date"])

In [59]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
1385,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
1386,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
1387,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
1388,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,Match Report,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [60]:
matches.dtypes

date            datetime64[us]
time                       str
comp                       str
round                      str
day                        str
venue                      str
result                     str
gf                     float64
ga                     float64
opponent                   str
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                    str
formation                  str
referee                    str
match report               str
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                       str
dtype: object

In [61]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [62]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [63]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [64]:
matches["day_code"] = matches["date"].dt.dayofweek

In [65]:
matches["target"] = (matches["result"] == 'W').astype("int")

In [66]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6,0
1385,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5,0
1386,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6,1
1387,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2,0
1388,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6,1

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [69]:
train = matches[matches["date"] < "2022-01-01"]

In [70]:
test = matches[matches["date"] > '2022-01-01']

In [71]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [72]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [73]:
preds = rf.predict(test[predictors])

In [74]:
from sklearn.metrics import accuracy_score

In [75]:
acc = accuracy_score(test["target"], preds)

In [76]:
acc

0.6123188405797102

In [77]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [78]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           141  31
1            76  28

In [79]:
from sklearn.metrics import precision_score

In [80]:
precision_score(test["target"], preds)

0.4745762711864407

In [81]:
# Rolling Averages
grouped_matches = matches.groupby("team")

In [82]:
group = grouped_matches.get_group("Manchester City")

In [83]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2.0,0.0,Crystal Palace,...,1.0,0.0,0.0,2021,Manchester City,0,6,12,5,1
663,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1.0,2.0,Chelsea,...,0.0,0.0,1.0,2021,Manchester City,1,5,17,5,0
664,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4.0,3.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,0,14,20,4,1
665,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2.0,3.0,Brighton,...,1.0,0.0,0.0,2021,Manchester City,0,3,19,1,0
666,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5.0,0.0,Everton,...,0.0,0.0,0.0,2021,Manchester City,1,7,16,6,1

In [84]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [85]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [86]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [87]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
632,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,...,5,1,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
633,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,...,5,0,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
634,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,...,5,1,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
635,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,...,6,0,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
636,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,...,5,0,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,D,0.0,0.0,Crystal Palace,...,0,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
29,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,W,2.0,0.0,Burnley,...,5,1,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
30,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,D,2.0,2.0,Liverpool,...,6,0,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
31,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,W,3.0,0.0,Brighton,...,2,1,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
32,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,5,1,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [88]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [89]:
matches_rolling

                                  date   time            comp         round  \
team
Arsenal                 898 2020-10-04  14:00  Premier League   Matchweek 4
                        899 2020-10-17  17:30  Premier League   Matchweek 5
                        900 2020-10-25  19:15  Premier League   Matchweek 6
                        901 2020-11-01  16:30  Premier League   Matchweek 7
                        902 2020-11-08  19:15  Premier League   Matchweek 8
...                                ...    ...             ...           ...
Wolverhampton Wanderers 227 2022-03-13  14:00  Premier League  Matchweek 29
                        228 2022-03-18  20:00  Premier League  Matchweek 30
                        229 2022-04-02  15:00  Premier League  Matchweek 31
                        230 2022-04-08  20:00  Premier League  Matchweek 32
                        231 2022-04-24  14:00  Premier League  Matchweek 34

                             day venue result   gf   ga         opponent  ...  \
team                                                                      ...
Arsenal                 898  Sun  Home      W  2.0  1.0    Sheffield Utd  ...
                        899  Sat  Away      L  0.0  1.0  Manchester City  ...
                        900  Sun  Home      L  0.0  1.0   Leicester City  ...
                        901  Sun  Away      W  1.0  0.0   Manchester Utd  ...
                        902  Sun  Home      L  0.0  3.0      Aston Villa  ...
...                          ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 227  Sun  Away      W  1.0  0.0          Everton  ...
                        228  Fri  Home      L  2.0  3.0     Leeds United  ...
                        229  Sat  Home      W  2.0  1.0      Aston Villa  ...
                        230  Fri  Away      L  0.0  1.0    Newcastle Utd  ...
                        231  Sun  Away      L  0.0  1.0          Burnley  ...

                             day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 898         6       1    2.000000    1.333333
                        899         5       0    1.666667    1.666667
                        900         6       0    1.000000    1.666667
                        901         6       1    0.666667    1.000000
                        902         6       0    0.333333    0.666667
...                               ...     ...         ...         ...
Wolverhampton Wanderers 227         6       1    1.333333    1.000000
                        228         4       0    1.666667    0.666667
                        229         5       1    2.333333    1.000000
                        230         4       0    1.666667    1.333333
                        231         6       0    1.333333    1.666667

                            sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 898   7.666667    3.666667    14.733333   0.666667
                        899   5.333333    3.666667    15.766667   0.000000
                        900   7.000000    3.666667    16.733333   0.666667
                        901   9.666667    4.000000    16.033333   1.000000
                        902   9.666667    2.666667    18.033333   1.000000
...                                ...         ...          ...        ...
Wolverhampton Wanderers 227  12.333333    3.666667    19.300000   0.000000
                        228  12.333333    4.333333    19.600000   0.000000
                        229  13.000000    5.333333    19.833333   0.000000
                        230  13.000000    5.000000    18.533333   0.000000
                        231  10.000000    4.666667    17.633333   0.000000

                             pk_rolling  pkatt_rolling
team
Arsenal                 898    0.000000       0.000000
                        899    0.000000       0.000000
                        900    0.000000       0.000000
                        901    0.000000       0.000000
                        902    0.333333       0.333333
...                                 ...            ...
Wolverhampton Wanderers 227    0.000000       0.000000
                        228    0.000000       0.000000
                        229    0.000000       0.000000
                        230    0.000000       0.000000
                        231    0.000000       0.000000

[1317 rows x 39 columns]

In [90]:
matches_rolling = matches_rolling.reset_index(level='team')

In [91]:
matches_rolling

,team,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,Arsenal,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,Arsenal,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,Arsenal,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,Arsenal,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,Arsenal,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,Wolverhampton Wanderers,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
228,Wolverhampton Wanderers,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
229,Wolverhampton Wanderers,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
230,Wolverhampton Wanderers,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
231,Wolverhampton Wanderers,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [92]:
matches_rolling.index = range(matches_rolling.shape[0])

In [93]:
matches_rolling

,team,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,Arsenal,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,Arsenal,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,Arsenal,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,Arsenal,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,Arsenal,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,Wolverhampton Wanderers,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,Wolverhampton Wanderers,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,Wolverhampton Wanderers,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,Wolverhampton Wanderers,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,Wolverhampton Wanderers,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [94]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [95]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [96]:
precision

0.625

In [97]:
combined

      actual  predicted
55         0          0
56         1          0
57         1          0
58         1          1
59         1          1
...      ...        ...
1312       1          0
1313       0          0
1314       1          0
1315       0          0
1316       0          0

[276 rows x 2 columns]

In [98]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [99]:
combined

,actual,predicted,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [101]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle Untited": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves"
}
mapping = MissingDict(**map_values)

In [102]:
mapping["Arsenal"]

'Arsenal'

In [103]:
mapping["West Ham United"]

'West Ham'

In [104]:
combined["new_team"] = combined["team"].map(mapping)

In [105]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [106]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [108]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves,0,0,Everton,Wolves,L,Everton
243,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United
244,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
245,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle United
246,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley

In [112]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

actual_x
1    23
0    11
Name: count, dtype: int64

In [113]:
23 / 34

0.6764705882352942